name: dht_dart
description: A DHT protocal implemented by Dart. This package implemented BEP-0005 for torrent client
version: 0.0.8
repository: https://github.com/eclipseglory/dht
issue_tracker: https://github.com/eclipseglory/dht/issues
publish_to: https://pub.dev/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bencode_dart: ^1.0.3
  dartorrent_common: ^1.0.4
dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.3
  torrent_model: ^1.0.4
